### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by vikramvk** [ExpediaDotCom/tesla#3]
I want to use [Sourcegraph](https://sourcegraph.com) for tesla code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/ExpediaDotCom/tesla. (It should only take 30 seconds.)

Thank you!

**Comment by vikramvk** [comment]
Hey Yunfei, I wanted to try out Sourcegraph with Tesla. Pls approve the request to enable it to be indexed.

**Comment by zwobill** [comment]
Done

**Comment by jamescuddy** [comment]
Hey @vikramvk - James from Sourcegraph here. Thanks for helping to enable Sourcegraph on this project. We would love to get your feedback once you start using Sourcgraph, please feel free to reach out to james@sourcegraph.com so we don't spam this thread!

**Comment by vikramvk** [comment]
Well, the person closed the issue but it still does not show up as enabled.
[image: Inline image 1]

**Comment by zwobill** [comment]
The Sourcegrahp is enabled. Please find it on https://sourcegraph.com/github.com/ExpediaDotCom/tesla/.builds/2248977.
